export enum TrackingStatusEnum {
  ORDER_RECEIVED = 'ORDER_RECEIVED',
  ITEMS_RESERVED = 'ITEMS_RESERVED',
  PICKING_ITEMS = 'PICKING_ITEMS',
  ITEMS_PICKED = 'ITEMS_PICKED',
  PACKING_ITEMS = 'PACKING_ITEMS',
  ITEMS_PACKED = 'ITEMS_PACKED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_PICKED_UP = 'ORDER_PICKED_UP',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  OTHER = 'OTHER',
}
