export enum MongoConstantsProvider {
  MongoConnection = 'DATABASE_CONNECTION',
  MongoUserSchema = 'USER_SCHEMA',
  MongoUserRepository = 'MONGO_USER_REPOSITORY',
  MongoAdminSchema = 'ADMIN_SCHEMA',
  MongoAdminRepository = 'MONGO_ADMIN_REPOSITORY',
  MongoInstitutionalTextSchema = 'INSTITUTIONAL_TEXT_SCHEMA',
  MongoInstitutionalTextRepository = 'MONGO_INSTITUTIONAL_TEXT_REPOSITORY',
  MongoQuoteSchema = 'QUOTE_SCHEMA',
  MongoQuoteRepository = 'MONGO_QUOTE_REPOSITORY',
  MongoTrackingSchema = 'TRACKING_SCHEMA',
  MongoTrackingRepository = 'MONGO_TRACKING_REPOSITORY',
  MongoSmsSchema = 'SMS_SCHEMA',
  MongoSmsRepository = 'MONGO_SMS_REPOSITORY',
  MongoEmailSchema = 'EMAIL_SCHEMA',
  MongoEmailRepository = 'MONGO_EMAIL_REPOSITORY',
  MongoWhatsAppSchema = 'WHATSAPP_SCHEMA',
  MongoWhatsAppRepository = 'MONGO_WHATSAPP_REPOSITORY',
  MongoMessageSchema = 'MESSAGE_SCHEMA',
  MongoMessageRepository = 'MONGO_MESSAGE_REPOSITORY',
  MongoCampaignSchema = 'CAMPAIGN_SCHEMA',
  MongoCampaignRepository = 'MONGO_CAMPAIGN_REPOSITORY',
}
